name: contact_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  file_picker: ^5.0.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  flutter_image_compress: ^1.1.3
  flutter_riverpod: ^1.0.4
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.6
  lottie: ^1.4.3
  path_provider: ^2.0.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"
  flutter_lints: ^2.0.0
  freezed: ^2.2.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  image_path_ios: "assets/icons/icon_ios.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/lottie/